import './globals.css';
import { Poppins } from 'next/font/google';
import Navigation from './_components/header/Navigation';

export const metadata = {
	title: `Tamara's Portfolio`,
	description: 'Generated by create next app',
};

const poppins = Poppins({
	subsets: ['latin'],
	weight: ['400', '600', '700'],
	variable: '--font-poppins',
});

export default function RootLayout({ children }) {
	return (
		<html lang='en' className={poppins.variable}>
			<body>
				<header className='w-full pb-24'>
					<Navigation />
				</header>
				<main className='pb-24 px-24 flex items-center justify-center'>
					{children}
				</main>
			</body>
		</html>
	);
}
